<?php

// DO NOT EDIT! This file is auto generated by 'Shopware\Core\Framework\Feature'}
namespace Symfony\Component\DependencyInjection\Loader\Configurator;

return static function(ContainerConfigurator $configurator) {
    $configurator->parameters()->set(
        'shopware.features',
        array (
  'FEATURE_NEXT_1797' => false,
  'FEATURE_NEXT_7453' => false,
  'FEATURE_NEXT_8172' => false,
  'FEATURE_NEXT_12009' => false,
  'FEATURE_NEXT_10549' => false,
  'FEATURE_NEXT_10078' => false,
  'FEATURE_NEXT_10539' => false,
  'FEATURE_NEXT_12092' => false,
  'FEATURE_NEXT_11253' => false,
  'FEATURE_NEXT_10550' => false,
  'FEATURE_NEXT_12016' => false,
  'FEATURE_NEXT_11917' => false,
  'FEATURE_NEXT_10553' => false,
  'FEATURE_NEXT_12108' => false,
  'FEATURE_NEXT_10552' => false,
  'FEATURE_NEXT_12553' => false,
  'FEATURE_NEXT_12608' => false,
  'FEATURE_NEXT_7365' => false,
  'FEATURE_NEXT_12289' => false,
  'FEATURE_NEXT_12032' => false,
  'FEATURE_NEXT_12942' => false,
  'FEATURE_NEXT_12957' => false,
  'FEATURE_NEXT_9831' => false,
  'FEATURE_NEXT_12429' => false,
)
    );
};