<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1GjE3xK\srcShopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1GjE3xK/srcShopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1GjE3xK.legacy');

    return;
}

if (!\class_exists(srcShopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1GjE3xK\srcShopware_Production_KernelDevDebugContainer::class, srcShopware_Production_KernelDevDebugContainer::class, false);
}

return new \Container1GjE3xK\srcShopware_Production_KernelDevDebugContainer([
    'container.build_hash' => '1GjE3xK',
    'container.build_id' => '148defe4',
    'container.build_time' => 1619295980,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1GjE3xK');
